In [1]:
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
years = list(range(1991,2026))

In [3]:
dfs = []
for year in years:
    with open("advanced_stats/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    player_table = soup.find_all(id="advanced")[0]
    player_df = pd.read_html(str(player_table))[0]
    player_df["Year"] = year
    dfs.append(player_df)

C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]
C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\2344917173.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_df = pd.read_html(str(player_table))[0]

In [4]:
player_advanced = pd.concat(dfs)

In [5]:
player_advanced.to_csv("player_advanced_og.csv", index=False)

In [29]:
player_advanced = pd.read_csv("player_advanced_og.csv")

In [18]:
player_advanced

,Rk,Player,Age,Team,Pos,G,GS,MP,PER,TS%,...,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Awards,Year
0,1,Chris Mullin,27,GSW,SF,82,82,3315,21.4,.618,...,9.7,2.4,12.2,.176,4.5,0.1,4.7,5.6,"AS,NBA2",1991
1,2,Karl Malone,27,UTA,PF,82,82,3302,24.8,.596,...,9.9,5.6,15.5,.225,4.8,0.6,5.4,6.2,"MVP-5,AS,NBA1",1991
2,3,Tim Hardaway,24,GSW,PG,82,82,3215,20.9,.547,...,7.4,2.5,9.9,.148,4.5,-0.1,4.4,5.2,"MVP-19,AS",1991
3,4,Tyrone Corbin,28,MIN,SF,82,82,3196,16.6,.499,...,2.6,2.9,5.4,.081,0.5,0.4,0.9,2.3,NaN,1991
4,5,Pooh Richardson,24,MIN,PG,82,82,3154,18.1,.492,...,4.5,1.3,5.9,.089,3.1,-1.1,2.0,3.2,NaN,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20901,566,James Wiseman,23,IND,C,1,0,5,31.2,.615,...,0.0,0.0,0.0,.237,6.0,-4.4,1.6,0.0,NaN,2025
20902,567,Alondes Williams,25,DET,SG,1,0,4,53.4,1.250,...,0.0,0.0,0.0,.565,37.9,6.2,44.1,0.0,NaN,2025
20903,568,Zyon Pullin,23,MEM,SG,3,0,3,-11.7,.000,...,0.0,0.0,0.0,-0.304,-15.0,-7.7,-22.7,0.0,NaN,2025
20904,569,Jahlil Okafor,29,IND,C,1,0,3,13.8,NaN,...,0.0,0.0,0.0,.196,2.5,4.9,7.5,0.0,NaN,2025
20905,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.576,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025

In [30]:
del player_advanced["Awards"]

In [20]:
player_advanced

,Rk,Player,Age,Team,Pos,G,GS,MP,PER,TS%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Year
0,1,Chris Mullin,27,GSW,SF,82,82,3315,21.4,.618,...,23.5,9.7,2.4,12.2,.176,4.5,0.1,4.7,5.6,1991
1,2,Karl Malone,27,UTA,PF,82,82,3302,24.8,.596,...,30.1,9.9,5.6,15.5,.225,4.8,0.6,5.4,6.2,1991
2,3,Tim Hardaway,24,GSW,PG,82,82,3215,20.9,.547,...,24.7,7.4,2.5,9.9,.148,4.5,-0.1,4.4,5.2,1991
3,4,Tyrone Corbin,28,MIN,SF,82,82,3196,16.6,.499,...,22.7,2.6,2.9,5.4,.081,0.5,0.4,0.9,2.3,1991
4,5,Pooh Richardson,24,MIN,PG,82,82,3154,18.1,.492,...,21.8,4.5,1.3,5.9,.089,3.1,-1.1,2.0,3.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20901,566,James Wiseman,23,IND,C,1,0,5,31.2,.615,...,42.2,0.0,0.0,0.0,.237,6.0,-4.4,1.6,0.0,2025
20902,567,Alondes Williams,25,DET,SG,1,0,4,53.4,1.250,...,21.1,0.0,0.0,0.0,.565,37.9,6.2,44.1,0.0,2025
20903,568,Zyon Pullin,23,MEM,SG,3,0,3,-11.7,.000,...,13.4,0.0,0.0,0.0,-0.304,-15.0,-7.7,-22.7,0.0,2025
20904,569,Jahlil Okafor,29,IND,C,1,0,3,13.8,NaN,...,0.0,0.0,0.0,0.0,.196,2.5,4.9,7.5,0.0,2025
20905,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.576,...,19.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025

In [31]:
player_advanced.to_csv("player_advanced.csv", index=False)

In [32]:
player_advanced = player_advanced.rename(columns={"Team": "Tm"})

In [23]:
player_advanced

,Rk,Player,Age,Tm,Pos,G,GS,MP,PER,TS%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Year
0,1,Chris Mullin,27,GSW,SF,82,82,3315,21.4,.618,...,23.5,9.7,2.4,12.2,.176,4.5,0.1,4.7,5.6,1991
1,2,Karl Malone,27,UTA,PF,82,82,3302,24.8,.596,...,30.1,9.9,5.6,15.5,.225,4.8,0.6,5.4,6.2,1991
2,3,Tim Hardaway,24,GSW,PG,82,82,3215,20.9,.547,...,24.7,7.4,2.5,9.9,.148,4.5,-0.1,4.4,5.2,1991
3,4,Tyrone Corbin,28,MIN,SF,82,82,3196,16.6,.499,...,22.7,2.6,2.9,5.4,.081,0.5,0.4,0.9,2.3,1991
4,5,Pooh Richardson,24,MIN,PG,82,82,3154,18.1,.492,...,21.8,4.5,1.3,5.9,.089,3.1,-1.1,2.0,3.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20901,566,James Wiseman,23,IND,C,1,0,5,31.2,.615,...,42.2,0.0,0.0,0.0,.237,6.0,-4.4,1.6,0.0,2025
20902,567,Alondes Williams,25,DET,SG,1,0,4,53.4,1.250,...,21.1,0.0,0.0,0.0,.565,37.9,6.2,44.1,0.0,2025
20903,568,Zyon Pullin,23,MEM,SG,3,0,3,-11.7,.000,...,13.4,0.0,0.0,0.0,-0.304,-15.0,-7.7,-22.7,0.0,2025
20904,569,Jahlil Okafor,29,IND,C,1,0,3,13.8,NaN,...,0.0,0.0,0.0,0.0,.196,2.5,4.9,7.5,0.0,2025
20905,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.576,...,19.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025

In [33]:
player_advanced[player_advanced["Player"] == "Greg Anderson"]

,Rk,Player,Age,Tm,Pos,G,GS,MP,PER,TS%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Year
274,239,Greg Anderson,26,3TM,PF,68,2,924,9.1,.455,...,16.3,-1.2,0.9,-0.3,-0.017,-5.1,-1.0,-6.1,-1.0,1991
275,239,Greg Anderson,26,MIL,PF,26,0,247,7.5,.410,...,18.6,-0.5,0.4,-0.1,-0.027,-5.8,-2.1,-7.9,-0.4,1991
276,239,Greg Anderson,26,NJN,PF,1,0,18,26.4,1.000,...,11.2,0.1,0.0,0.1,.300,5.1,4.5,9.6,0.1,1991
277,239,Greg Anderson,26,DEN,PF,41,2,659,9.2,.463,...,15.6,-0.8,0.5,-0.3,-0.022,-5.2,-0.7,-5.9,-0.7,1991
492,40,Greg Anderson,27,DEN,PF,82,82,2793,12.6,.486,...,17.1,-0.6,3.6,3.0,.052,-2.4,-1.1,-3.4,-1.0,1992
1555,153,Greg Anderson,29,DET,PF,77,47,1624,14.6,.561,...,14.3,1.4,2.0,3.4,.101,-1.7,0.1,-1.6,0.2,1994
2191,282,Greg Anderson,30,ATL,PF,51,0,622,12.6,.547,...,12.2,0.3,1.3,1.5,.118,-3.9,1.7,-2.2,0.0,1995
2780,336,Greg Anderson,31,SAS,PF,46,7,344,7.7,.466,...,10.5,-0.3,0.7,0.4,.056,-6.2,2.6,-3.5,-0.1,1996
3095,167,Greg Anderson,32,SAS,C,82,48,1659,11.4,.531,...,10.5,0.7,1.5,2.2,.064,-3.6,0.1,-3.5,-0.6,1997
3918,329,Greg Anderson,33,ATL,C,50,0,398,10.4,.444,...,13.5,0.0,0.7,0.7,.090,-4.3,0.9,-3.4,-0.1,1998

In [25]:
player_advanced.groupby(["Player", "Year"]).get_group(("Greg Anderson", 1991))

,Rk,Player,Age,Tm,Pos,G,GS,MP,PER,TS%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Year
274,239,Greg Anderson,26,3TM,PF,68,2,924,9.1,.455,...,16.3,-1.2,0.9,-0.3,-0.017,-5.1,-1.0,-6.1,-1.0,1991
275,239,Greg Anderson,26,MIL,PF,26,0,247,7.5,.410,...,18.6,-0.5,0.4,-0.1,-0.027,-5.8,-2.1,-7.9,-0.4,1991
276,239,Greg Anderson,26,NJN,PF,1,0,18,26.4,1.000,...,11.2,0.1,0.0,0.1,.300,5.1,4.5,9.6,0.1,1991
277,239,Greg Anderson,26,DEN,PF,41,2,659,9.2,.463,...,15.6,-0.8,0.5,-0.3,-0.022,-5.2,-0.7,-5.9,-0.7,1991

In [34]:
def single_row(df):
    if df.shape[0] == 1: 
        return df
    else:
        row = df[df["Tm"].isin(["2TM", "3TM", "4TM", "5TM", "6TM", "7TM", "8TM", "9TM", "10TM"])]
        return row
player_advanced = player_advanced.groupby(["Player", "Year"]).apply(single_row)

C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\4020004183.py:7: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  player_advanced = player_advanced.groupby(["Player", "Year"]).apply(single_row)

In [35]:
player_advanced[player_advanced["Player"] == "Greg Anderson"]

                          Rk         Player Age   Tm Pos   G  GS    MP   PER  \
Player        Year
Greg Anderson 1991 274   239  Greg Anderson  26  3TM  PF  68   2   924   9.1
              1992 492    40  Greg Anderson  27  DEN  PF  82  82  2793  12.6
              1994 1555  153  Greg Anderson  29  DET  PF  77  47  1624  14.6
              1995 2191  282  Greg Anderson  30  ATL  PF  51   0   622  12.6
              1996 2780  336  Greg Anderson  31  SAS  PF  46   7   344   7.7
              1997 3095  167  Greg Anderson  32  SAS   C  82  48  1659  11.4
              1998 3918  329  Greg Anderson  33  ATL   C  50   0   398  10.4

                          TS%  ...  USG%   OWS  DWS    WS   WS/48  OBPM  DBPM  \
Player        Year             ...
Greg Anderson 1991 274   .455  ...  16.3  -1.2  0.9  -0.3  -0.017  -5.1  -1.0
              1992 492   .486  ...  17.1  -0.6  3.6   3.0    .052  -2.4  -1.1
              1994 1555  .561  ...  14.3   1.4  2.0   3.4    .101  -1.7   0.1
              1995 2191  .547  ...  12.2   0.3  1.3   1.5    .118  -3.9   1.7
              1996 2780  .466  ...  10.5  -0.3  0.7   0.4    .056  -6.2   2.6
              1997 3095  .531  ...  10.5   0.7  1.5   2.2    .064  -3.6   0.1
              1998 3918  .444  ...  13.5   0.0  0.7   0.7    .090  -4.3   0.9

                          BPM  VORP  Year
Player        Year
Greg Anderson 1991 274   -6.1  -1.0  1991
              1992 492   -3.4  -1.0  1992
              1994 1555  -1.6   0.2  1994
              1995 2191  -2.2   0.0  1995
              1996 2780  -3.5  -0.1  1996
              1997 3095  -3.5  -0.6  1997
              1998 3918  -3.4  -0.1  1998

[7 rows x 29 columns]

In [36]:
player_advanced

                           Rk          Player Age   Tm Pos   G  GS    MP  \
Player         Year
A.C. Green     1991 117   106      A.C. Green  27  LAL  PF  82  21  2164
               1992 482    30      A.C. Green  28  LAL  PF  82  53  2902
               1993 955    33      A.C. Green  29  LAL  PF  82  55  2819
               1994 1411   28      A.C. Green  30  PHO  PF  82  55  2825
               1995 1923   44      A.C. Green  31  PHO  SF  82  52  2687
...                       ...             ...  ..  ...  ..  ..  ..   ...
Željko Rebrača 2002 5902  228  Željko Rebrača  29  DET   C  74   4  1179
               2003 6512  315  Željko Rebrača  30  DET   C  30  12   488
               2004 7130  358  Željko Rebrača  31  2TM   C  24   2   273
               2005 7599  278  Željko Rebrača  32  LAC   C  58   2   928
               2006 8258  334  Željko Rebrača  33  LAC   C  29   2   412

                           PER   TS%  ...  USG%  OWS  DWS   WS WS/48  OBPM  \
Player         Year                   ...
A.C. Green     1991 117   13.8  .556  ...  15.6  3.2  2.9  6.1  .135   0.1
               1992 482   16.7  .556  ...  16.8  5.8  2.9  8.8  .145   1.7
               1993 955   16.3  .603  ...  15.0  6.1  2.6  8.6  .147   1.6
               1994 1411  17.0  .555  ...  17.6  6.7  2.6  9.3  .157   1.8
               1995 1923  14.2  .596  ...  14.2  4.6  2.1  6.7  .120   0.8
...                        ...   ...  ...   ...  ...  ...  ...   ...   ...
Željko Rebrača 2002 5902  16.2  .569  ...  21.4  1.4  1.9  3.3  .134  -2.9
               2003 6512  14.0  .596  ...  19.2  0.7  0.7  1.3  .133  -2.8
               2004 7130  10.5  .504  ...  18.2  0.1  0.4  0.5  .097  -4.5
               2005 7599  14.0  .625  ...  16.0  1.4  0.9  2.4  .122  -1.7
               2006 8258  10.7  .592  ...  15.5  0.2  0.5  0.7  .086  -3.7

                          DBPM   BPM  VORP  Year
Player         Year
A.C. Green     1991 117   -0.2   0.0   1.1  1991
               1992 482   -1.0   0.7   2.0  1992
               1993 955   -0.9   0.7   1.9  1993
               1994 1411  -1.2   0.6   1.8  1994
               1995 1923  -0.9  -0.1   1.3  1995
...                        ...   ...   ...   ...
Željko Rebrača 2002 5902   0.6  -2.3  -0.1  2002
               2003 6512   0.2  -2.6  -0.1  2003
               2004 7130   0.6  -3.9  -0.1  2004
               2005 7599   0.4  -1.3   0.2  2005
               2006 8258   0.9  -2.8  -0.1  2006

[16412 rows x 29 columns]

In [37]:
player_advanced.index = player_advanced.index.droplevel()
player_advanced.index = player_advanced.index.droplevel()

In [38]:
player_advanced

,Rk,Player,Age,Tm,Pos,G,GS,MP,PER,TS%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Year
117,106,A.C. Green,27,LAL,PF,82,21,2164,13.8,.556,...,15.6,3.2,2.9,6.1,.135,0.1,-0.2,0.0,1.1,1991
482,30,A.C. Green,28,LAL,PF,82,53,2902,16.7,.556,...,16.8,5.8,2.9,8.8,.145,1.7,-1.0,0.7,2.0,1992
955,33,A.C. Green,29,LAL,PF,82,55,2819,16.3,.603,...,15.0,6.1,2.6,8.6,.147,1.6,-0.9,0.7,1.9,1993
1411,28,A.C. Green,30,PHO,PF,82,55,2825,17.0,.555,...,17.6,6.7,2.6,9.3,.157,1.8,-1.2,0.6,1.8,1994
1923,44,A.C. Green,31,PHO,SF,82,52,2687,14.2,.596,...,14.2,4.6,2.1,6.7,.120,0.8,-0.9,-0.1,1.3,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5902,228,Željko Rebrača,29,DET,C,74,4,1179,16.2,.569,...,21.4,1.4,1.9,3.3,.134,-2.9,0.6,-2.3,-0.1,2002
6512,315,Željko Rebrača,30,DET,C,30,12,488,14.0,.596,...,19.2,0.7,0.7,1.3,.133,-2.8,0.2,-2.6,-0.1,2003
7130,358,Željko Rebrača,31,2TM,C,24,2,273,10.5,.504,...,18.2,0.1,0.4,0.5,.097,-4.5,0.6,-3.9,-0.1,2004
7599,278,Željko Rebrača,32,LAC,C,58,2,928,14.0,.625,...,16.0,1.4,0.9,2.4,.122,-1.7,0.4,-1.3,0.2,2005
8258,334,Željko Rebrača,33,LAC,C,29,2,412,10.7,.592,...,15.5,0.2,0.5,0.7,.086,-3.7,0.9,-2.8,-0.1,2006

In [39]:
pd.isnull(player_advanced).sum()

Rk        35
Player     0
Age       35
Tm        35
Pos       35
G         35
GS        35
MP        35
PER       38
TS%       62
3PAr      68
FTr       68
ORB%       3
DRB%       3
TRB%       3
AST%       3
STL%       3
BLK%       3
TOV%      52
USG%       3
OWS       35
DWS       35
WS        35
WS/48     38
OBPM      38
DBPM      38
BPM       38
VORP      35
Year       0
dtype: int64

In [40]:
player_advanced[pd.isnull(player_advanced["Age"])][["Player", "Age"]].head()

              Player  Age
452   League Average  NaN
922   League Average  NaN
1383  League Average  NaN
1877  League Average  NaN
2341  League Average  NaN

In [ ]:
player_advanced = player_advanced[player_advanced["Player"] != "League Average"]
player_advanced = player_advanced[player_advanced["Player"] != "Player"]

In [43]:
pd.isnull(player_advanced).sum()

Rk         0
Player     0
Age        0
Tm         0
Pos        0
G          0
GS         0
MP         0
PER        3
TS%       62
3PAr      68
FTr       68
ORB%       3
DRB%       3
TRB%       3
AST%       3
STL%       3
BLK%       3
TOV%      52
USG%       3
OWS        0
DWS        0
WS         0
WS/48      3
OBPM       3
DBPM       3
BPM        3
VORP       0
Year       0
dtype: int64

In [44]:
player_advanced[pd.isnull(player_advanced["TS%"])][["Player", "TS%"]]

                    Player  TS%
18696           Ade Murkey  NaN
4052       Adrian Caldwell  NaN
8425           Alex Scales  NaN
19390     Alondes Williams  NaN
5635            Andy Panko  NaN
...                    ...  ...
4564         Trevor Winter  NaN
15738  Trey McKinney-Jones  NaN
18688           Tyler Hall  NaN
15735          Tyler Lydon  NaN
16467           Tyler Ulis  NaN

[62 rows x 2 columns]

In [45]:
player_advanced = player_advanced.fillna(0)

In [46]:
player_advanced.dtypes

Rk        object
Player    object
Age       object
Tm        object
Pos       object
G         object
GS        object
MP        object
PER       object
TS%       object
3PAr      object
FTr       object
ORB%      object
DRB%      object
TRB%      object
AST%      object
STL%      object
BLK%      object
TOV%      object
USG%      object
OWS       object
DWS       object
WS        object
WS/48     object
OBPM      object
DBPM      object
BPM       object
VORP      object
Year       int64
dtype: object

In [47]:
player_advanced = player_advanced.apply(pd.to_numeric, errors="ignore")

C:\Users\Daniel\AppData\Local\Temp\ipykernel_33704\828313565.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  player_advanced = player_advanced.apply(pd.to_numeric, errors="ignore")

In [48]:
player_advanced.dtypes

Rk          int64
Player     object
Age         int64
Tm         object
Pos        object
G           int64
GS          int64
MP          int64
PER       float64
TS%       float64
3PAr      float64
FTr       float64
ORB%      float64
DRB%      float64
TRB%      float64
AST%      float64
STL%      float64
BLK%      float64
TOV%      float64
USG%      float64
OWS       float64
DWS       float64
WS        float64
WS/48     float64
OBPM      float64
DBPM      float64
BPM       float64
VORP      float64
Year        int64
dtype: object

In [49]:
player_advanced = player_advanced.drop(["Age", "G", "GS", "Tm", "MP", "Pos"], axis=1)

In [50]:
player_advanced

,Rk,Player,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Year
117,106,A.C. Green,13.8,0.556,0.101,0.557,11.3,16.2,13.8,4.5,...,15.6,3.2,2.9,6.1,0.135,0.1,-0.2,0.0,1.1,1991
482,30,A.C. Green,16.7,0.556,0.070,0.569,11.8,18.2,14.9,6.0,...,16.8,5.8,2.9,8.8,0.145,1.7,-1.0,0.7,2.0,1992
955,33,A.C. Green,16.3,0.603,0.065,0.531,11.5,17.3,14.4,5.9,...,15.0,6.1,2.6,8.6,0.147,1.6,-0.9,0.7,1.9,1993
1411,28,A.C. Green,17.0,0.555,0.038,0.391,11.1,18.8,15.0,6.9,...,17.6,6.7,2.6,9.3,0.157,1.8,-1.2,0.6,1.8,1994
1923,44,A.C. Green,14.2,0.596,0.206,0.556,8.3,20.4,14.3,6.5,...,14.2,4.6,2.1,6.7,0.120,0.8,-0.9,-0.1,1.3,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5902,228,Željko Rebrača,16.2,0.569,0.000,0.468,8.4,20.5,14.5,5.7,...,21.4,1.4,1.9,3.3,0.134,-2.9,0.6,-2.3,-0.1,2002
6512,315,Željko Rebrača,14.0,0.596,0.000,0.331,6.5,16.0,11.2,3.6,...,19.2,0.7,0.7,1.3,0.133,-2.8,0.2,-2.6,-0.1,2003
7130,358,Željko Rebrača,10.5,0.504,0.000,0.390,9.9,14.6,12.2,4.0,...,18.2,0.1,0.4,0.5,0.097,-4.5,0.6,-3.9,-0.1,2004
7599,278,Željko Rebrača,14.0,0.625,0.000,0.363,6.5,16.9,11.9,4.8,...,16.0,1.4,0.9,2.4,0.122,-1.7,0.4,-1.3,0.2,2005
8258,334,Željko Rebrača,10.7,0.592,0.000,0.427,3.8,13.8,9.0,3.5,...,15.5,0.2,0.5,0.7,0.086,-3.7,0.9,-2.8,-0.1,2006

In [51]:
player_advanced.to_csv("player_advanced.csv", index=False)

In [55]:
player_per_game = pd.read_csv("player_mvp_stats.csv")
del player_per_game["Unnamed: 0"]
player_per_game = player_per_game.fillna(0)

In [56]:
player_per_game

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,SF,32,PHO,82,36,25.8,2.6,5.4,0.484,...,0.0,0.0,Phoenix Suns,41,41,0.500,23.0,104.3,104.0,0.28
1,A.C. Green,PF,37,MIA,82,1,17.2,1.8,4.0,0.444,...,0.0,0.0,Miami Heat,50,32,0.610,6.0,88.9,86.6,1.73
2,A.C. Green,PF,33,DAL,83,73,30.0,2.8,5.8,0.483,...,0.0,0.0,Dallas Mavericks,24,58,0.293,40.0,90.6,97.0,-6.47
3,A.C. Green,PF,34,DAL,82,68,32.3,3.0,6.5,0.453,...,0.0,0.0,Dallas Mavericks,20,62,0.244,42.0,91.4,97.5,-6.33
4,A.C. Green,PF,35,DAL,50,35,18.5,2.2,5.1,0.422,...,0.0,0.0,Dallas Mavericks,19,31,0.380,18.0,91.6,94.0,-2.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16046,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,0.552,...,0.0,0.0,Detroit Pistons,50,32,0.610,0.0,91.4,87.7,2.97
16047,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,0.505,...,0.0,0.0,Detroit Pistons,50,32,0.610,0.0,94.3,92.2,1.69
16048,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,0.568,...,0.0,0.0,Los Angeles Clippers,37,45,0.451,25.0,95.7,96.5,-0.47
16049,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,0.542,...,0.0,0.0,Los Angeles Clippers,47,35,0.573,7.0,97.2,95.6,1.75
16050,Željko Rebrača,C,31,ATL,24,2,11.4,1.4,3.2,0.442,...,0.0,0.0,Atlanta Hawks,28,54,0.341,33.0,92.8,97.5,-5.00

In [63]:
all_stats = player_per_game.merge(player_advanced, how="inner", on=["Player", "Year"])

In [64]:
all_stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,A.C. Green,SF,32,PHO,82,36,25.8,2.6,5.4,0.484,...,12.6,13.2,2.7,1.7,4.4,0.100,-0.4,-0.9,-1.3,0.4
1,A.C. Green,PF,37,MIA,82,1,17.2,1.8,4.0,0.444,...,10.8,14.4,1.1,2.1,3.2,0.110,-2.2,0.0,-2.2,-0.1
2,A.C. Green,PF,33,DAL,83,73,30.0,2.8,5.8,0.483,...,11.5,11.8,2.4,2.4,4.8,0.093,-1.0,-0.4,-1.4,0.4
3,A.C. Green,PF,34,DAL,82,68,32.3,3.0,6.5,0.453,...,10.1,11.6,2.8,2.4,5.2,0.095,-1.1,-0.3,-1.4,0.4
4,A.C. Green,PF,35,DAL,50,35,18.5,2.2,5.1,0.422,...,6.4,14.8,0.7,0.7,1.4,0.074,-1.1,-1.1,-2.2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16028,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,0.552,...,14.9,19.2,0.7,0.7,1.3,0.133,-2.8,0.2,-2.6,-0.1
16029,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,0.505,...,15.7,21.4,1.4,1.9,3.3,0.134,-2.9,0.6,-2.3,-0.1
16030,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,0.568,...,15.3,16.0,1.4,0.9,2.4,0.122,-1.7,0.4,-1.3,0.2
16031,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,0.542,...,17.4,15.5,0.2,0.5,0.7,0.086,-3.7,0.9,-2.8,-0.1
16032,Željko Rebrača,C,31,ATL,24,2,11.4,1.4,3.2,0.442,...,15.9,18.2,0.1,0.4,0.5,0.097,-4.5,0.6,-3.9,-0.1

In [65]:
all_stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS', 'Rk', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%',
       'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS', 'DWS', 'WS',
       'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP'],
      dtype='object')

In [67]:
all_stats.to_csv("all_stats.csv", index=False)